apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "authelia.name" . }}
    app.kubernetes.io/component: {{ .Values.authelia.fullname }}
    helm.sh/chart: {{ include "authelia.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "authelia.name" . }}
    app.kubernetes.io/component: {{ .Values.authelia.fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
